-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 12:16:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`id_avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id_avion` (
  `id_avion` INT NOT NULL,
  `capacidad_personas` TINYINT(3) NOT NULL,
  PRIMARY KEY (`id_avion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`id_asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id_asientos` (
  `id_asientos` INT NOT NULL,
  `id_avion_id_avion` INT NOT NULL,
  PRIMARY KEY (`id_asientos`),
  INDEX `fk_id_asientos_id_avion_idx` (`id_avion_id_avion` ASC) VISIBLE,
  CONSTRAINT `fk_id_asientos_id_avion`
    FOREIGN KEY (`id_avion_id_avion`)
    REFERENCES `mydb`.`id_avion` (`id_avion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`id_pintor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id_pintor` (
  `id_pintor` INT NOT NULL,
  `nombre_pintor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pintor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`id_cuadro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`id_cuadro` (
  `id_cuadro` INT NOT NULL AUTO_INCREMENT,
  `precio` SMALLINT(10) NULL,
  `id_pintor_id_pintor` INT NOT NULL,
  PRIMARY KEY (`id_cuadro`),
  INDEX `fk_id_cuadro_id_pintor1_idx` (`id_pintor_id_pintor` ASC) VISIBLE,
  CONSTRAINT `fk_id_cuadro_id_pintor1`
    FOREIGN KEY (`id_pintor_id_pintor`)
    REFERENCES `mydb`.`id_pintor` (`id_pintor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`idCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`idCliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NULL,
  `DNI` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `idCliente_idCliente` INT NOT NULL,
  `id_cuadro_id_cuadro` INT NOT NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventas_idCliente1_idx` (`idCliente_idCliente` ASC) VISIBLE,
  INDEX `fk_ventas_id_cuadro1_idx` (`id_cuadro_id_cuadro` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_idCliente1`
    FOREIGN KEY (`idCliente_idCliente`)
    REFERENCES `mydb`.`idCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_id_cuadro1`
    FOREIGN KEY (`id_cuadro_id_cuadro`)
    REFERENCES `mydb`.`id_cuadro` (`id_cuadro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `n_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `n_usuario_UNIQUE` (`n_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos_has_usuario` (
  `videos_idvideos` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `id_usuario_video` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`videos_idvideos`, `usuario_id_usuario`, `id_usuario_video`),
  INDEX `fk_videos_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_videos_has_usuario_videos1_idx` (`videos_idvideos` ASC) VISIBLE,
  CONSTRAINT `fk_videos_has_usuario_videos1`
    FOREIGN KEY (`videos_idvideos`)
    REFERENCES `mydb`.`videos` (`idvideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `idvideos` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripción` VARCHAR(45) NULL,
  `URL` VARCHAR(45) NULL,
  `videoscol` VARCHAR(45) NULL,
  `videos_has_usuario_id_usuario_video` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvideos`),
  INDEX `fk_videos_videos_has_usuario1_idx` (`videos_has_usuario_id_usuario_video` ASC) VISIBLE,
  CONSTRAINT `fk_videos_videos_has_usuario1`
    FOREIGN KEY (`videos_has_usuario_id_usuario_video`)
    REFERENCES `mydb`.`videos_has_usuario` (`id_usuario_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `idautores` INT NOT NULL,
  `dirección` VARCHAR(45) NULL,
  `n_libros_escritos` TINYINT(2) NULL,
  PRIMARY KEY (`idautores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libros` (
  `idLibros` INT NOT NULL,
  `en_venta` BINARY(1) NULL,
  `unidades` SMALLINT(5) NULL,
  `precio` SMALLINT(5) NULL,
  `autores_idautores` INT NOT NULL,
  PRIMARY KEY (`idLibros`),
  INDEX `fk_Libros_autores1_idx` (`autores_idautores` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_autores1`
    FOREIGN KEY (`autores_idautores`)
    REFERENCES `mydb`.`autores` (`idautores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idfactura` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `Libros_idLibros` INT NOT NULL,
  INDEX `fk_Ventas_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_Ventas_Libros1_idx` (`Libros_idLibros` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Libros1`
    FOREIGN KEY (`Libros_idLibros`)
    REFERENCES `mydb`.`Libros` (`idLibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amistades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amistades` (
  `idamistades` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `usuarios_idusuarios1` INT NOT NULL,
  `como_se_conocieron` VARCHAR(45) NULL,
  PRIMARY KEY (`idamistades`),
  INDEX `fk_amistades_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_amistades_usuarios2_idx` (`usuarios_idusuarios1` ASC) VISIBLE,
  CONSTRAINT `fk_amistades_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amistades_usuarios2`
    FOREIGN KEY (`usuarios_idusuarios1`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fotografias` (
  `idfotografias` INT NOT NULL,
  `dirección` VARCHAR(45) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idfotografias`),
  INDEX `fk_fotografias_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_fotografias_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`URL_Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`URL_Foto` (
  `idURL_Foto` INT NOT NULL,
  `fotografias_idfotografias` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idURL_Foto`),
  INDEX `fk_URL_Foto_fotografias1_idx` (`fotografias_idfotografias` ASC) VISIBLE,
  INDEX `fk_URL_Foto_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_URL_Foto_fotografias1`
    FOREIGN KEY (`fotografias_idfotografias`)
    REFERENCES `mydb`.`fotografias` (`idfotografias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_URL_Foto_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `idProveedor` INT NOT NULL,
  `Nombre_proveedor` VARCHAR(45) NULL,
  `calle_proveedor` VARCHAR(45) NULL,
  `numero_proveedor` VARCHAR(45) NULL,
  `piso_proveedor` VARCHAR(45) NULL,
  `puerta_proveedor` VARCHAR(45) NULL,
  `ciudad_proveedor` VARCHAR(45) NULL,
  `codigo_postal_proveedor` VARCHAR(45) NULL,
  `Pais_proveedor` VARCHAR(45) NULL,
  `Telf_proveedor` VARCHAR(45) NULL,
  `Fax_proveedor` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gafas` (
  `idGafas` INT NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `graduació` VARCHAR(45) NULL,
  `tipo_montura` VARCHAR(45) NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_cristal` VARCHAR(45) NULL,
  `precio_gafa` SMALLINT(4) NULL,
  `Proveedores_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idGafas`),
  INDEX `fk_Gafas_Proveedores1_idx` (`Proveedores_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Gafas_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `mydb`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre_cliente` VARCHAR(45) NULL,
  `direccion_cliente` VARCHAR(45) NULL,
  `telf_cliente` VARCHAR(45) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recomendaciones clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recomendaciones clientes` (
)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Clientes_AFTER_INSERT` AFTER INSERT ON `Clientes` FOR EACH ROW
BEGIN

END
$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`recomendaciones clientes_AFTER_INSERT` AFTER INSERT ON `recomendaciones clientes` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
